name = "NORQAIN Customer Account App"
client_id = "5a1c150e56f25a19afb5d682403a9081"
application_url = "https://norqain.com"
embedded = false

[access_scopes]
scopes = "read_customers"

[auth]
redirect_urls = ["https://norqain.com/auth/callback"]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
