name = "NORQAIN Customer Account App"
client_id = "80b45bec40b8df82a089e0191dcdd9e3"
application_url = "https://norqain.com"
embedded = false

[access_scopes]
scopes = "read_customers"

[auth]
redirect_urls = ["https://norqain.com/auth/callback"]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
